# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 19:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veredas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('dptompio', models.CharField(max_length=80)),
                ('codigo_ver', models.CharField(max_length=80)),
                ('nom_dep', models.CharField(max_length=80)),
                ('nomb_mpio', models.CharField(max_length=80)),
                ('nombre_ver', models.CharField(max_length=80)),
                ('vigencia', models.CharField(max_length=80)),
                ('fuente', models.CharField(max_length=80)),
                ('descripcio', models.CharField(max_length=80)),
                ('seudonimos', models.CharField(max_length=250)),
                ('area_ha', models.FloatField()),
                ('cod_dpto', models.CharField(max_length=80)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
