# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 19:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del Proyecto')),
                ('main_goal', models.CharField(max_length=500, verbose_name='Objetivo principal')),
                ('beneficiary', models.CharField(choices=[('Individuos', 'Individuos'), ('Instituciones', 'Instituciones'), ('Familias', 'Familias')], max_length=30, verbose_name='Beneficiarios')),
                ('beneficiary_comments', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones sobre los beneficiarios')),
                ('no_benef', models.IntegerField(verbose_name='Número de Beneficiarios')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de finalización')),
                ('budget', models.IntegerField(blank=True, null=True, verbose_name='Monto de ejecución')),
                ('representative', models.CharField(choices=[('Ninguna', 'Ninguna'), ('Secretaría de Gobierno y Servicios Administrativos', 'Secretaría de Gobierno y Servicios Administrativos'), ('Secretaría Local de Salud', 'Secretaría Local de Salud'), ('Tesorería de Rentas', 'Tesorería de Rentas'), ('Secretaría de Planeación y Obras Municipales', 'Secretaría de Planeación y Obras Municipales'), ('Secretaría para la Educación para la Cultura y el Desarrollo', 'Secretaría para la Educación para la Cultura y el Desarrollo')], max_length=200, verbose_name='Interlocutor')),
                ('lines_pd', models.CharField(choices=[('Ninguna', 'Ninguna'), ('Briceño con inclusión social para la paz', 'Briceño con inclusión social para la paz'), ('Cambio para el desarrollo económico de Briceño', 'Cambio para el desarrollo económico de Briceño'), ('Briceño legal, transparente, seguro y en paz', 'Briceño legal, transparente, seguro y en paz'), ('Briceño sostenible y protector del medio ambiente', 'Briceño sostenible y protector del medio ambiente')], max_length=200, verbose_name='Líneas del plan que impactan')),
                ('closed', models.BooleanField(default=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50, verbose_name='Tarea')),
                ('completion', models.CharField(choices=[('PI', 'Por iniciar'), ('EC', 'En curso'), ('TE', 'Terminada')], default=False, max_length=20, verbose_name='Estado')),
                ('comments', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.Project')),
            ],
            options={
                'verbose_name': 'Tarea del proyecto',
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.AlterModelOptions(
            name='veredas',
            options={'verbose_name': 'Vereda', 'verbose_name_plural': 'Veredas'},
        ),
        migrations.AddField(
            model_name='project',
            name='coverage',
            field=models.ManyToManyField(to='projects.Veredas', verbose_name='Veredas beneficiadas'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
