# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20171002_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='beneficiary',
            field=models.CharField(choices=[('Individuos', 'Individuos'), ('Instituciones', 'Instituciones'), ('Familias', 'Familias')], max_length=30, verbose_name='Tipo de beneficiarios'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.IntegerField(blank=True, help_text='Cifra en pesos colombianos', null=True, verbose_name='Monto de ejecución'),
        ),
        migrations.AlterField(
            model_name='project',
            name='coverage',
            field=models.ManyToManyField(help_text='Usar Crtl para seleccionar más de una opción.', to='projects.Veredas', verbose_name='Veredas beneficiadas'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(help_text='Seleccionar en el calendario.', verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lines_pd',
            field=models.CharField(choices=[('Ninguna', 'Ninguna'), ('Briceño con inclusión social para la paz', 'Briceño con inclusión social para la paz'), ('Cambio para el desarrollo económico de Briceño', 'Cambio para el desarrollo económico de Briceño'), ('Briceño legal, transparente, seguro y en paz', 'Briceño legal, transparente, seguro y en paz'), ('Briceño sostenible y protector del medio ambiente', 'Briceño sostenible y protector del medio ambiente')], max_length=200, verbose_name='Líneas del plan de desarrollo que impacta'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre del proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='no_benef',
            field=models.IntegerField(verbose_name='Número de beneficiarios'),
        ),
        migrations.AlterField(
            model_name='project',
            name='representative',
            field=models.CharField(choices=[('Ninguna', 'Ninguna'), ('Secretaría de Gobierno y Servicios Administrativos', 'Secretaría de Gobierno y Servicios Administrativos'), ('Secretaría Local de Salud', 'Secretaría Local de Salud'), ('Tesorería de Rentas', 'Tesorería de Rentas'), ('Secretaría de Planeación y Obras Municipales', 'Secretaría de Planeación y Obras Municipales'), ('Secretaría para la Educación para la Cultura y el Desarrollo', 'Secretaría para la Educación para la Cultura y el Desarrollo')], max_length=200, verbose_name='Interlocutor en el municipio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(help_text='Seleccionar en el calendario.', verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='completion',
            field=models.CharField(choices=[('Por iniciar', 'Por iniciar'), ('En curso', 'En curso'), ('Terminada', 'Terminada')], default=False, max_length=20, verbose_name='Estado de ejecución'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='task',
            field=models.CharField(max_length=50, verbose_name='Actividad'),
        ),
    ]
