# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20171020_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='comments',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Título'),
        ),
    ]
