# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20171020_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='beneficiary_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones sobre los beneficiarios'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='comments',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.upload_location, verbose_name='Imagen'),
        ),
    ]
