# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='task',
            field=models.CharField(max_length=255, verbose_name='Actividad'),
        ),
    ]
