# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20171124_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='task_type',
            field=models.CharField(choices=[('Actividad', 'Actividad'), ('Proceso', 'Proceso'), ('Línea o programa', 'Línea o programa')], default=False, max_length=20, verbose_name='Tipo de producto'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones'),
        ),
    ]
