# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20171124_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='task_type',
            field=models.CharField(choices=[('Actividad', 'Actividad'), ('Proceso', 'Proceso'), ('Línea o programa', 'Línea o programa')], default='Actividad', max_length=20, verbose_name='Tipo de producto'),
        ),
    ]
