# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20171124_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.IntegerField(blank=True, default=0, help_text='Cifra en pesos colombianos', null=True, verbose_name='Monto de ejecución'),
        ),
        migrations.AlterField(
            model_name='project',
            name='no_benef',
            field=models.IntegerField(default=0, verbose_name='Número de destinatarios'),
        ),
    ]
