# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import entities.models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_userprofile_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization_logo',
            field=models.ImageField(blank=True, null=True, upload_to=entities.models.upload_location),
        ),
    ]
