# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_auto_20171020_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='some', max_length=255, unique=True, verbose_name='Nombre de usuario'),
            preserve_default=False,
        ),
    ]
