# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Entidad', 'entidad'), ('Consulta', 'consulta')], default='Entidad', max_length=10, verbose_name='Rol'),
            preserve_default=False,
        ),
    ]
