# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('entidad', 'Entidad'), ('consulta', 'Consulta')], max_length=10, verbose_name='Rol'),
        ),
    ]
